#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QuanLyNhanVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoAnQuanLyNhaThuoc")]
	public partial class DataQuanLyNhaThuocDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoaiUser(LoaiUser instance);
    partial void UpdateLoaiUser(LoaiUser instance);
    partial void DeleteLoaiUser(LoaiUser instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDonThuoc(DonThuoc instance);
    partial void UpdateDonThuoc(DonThuoc instance);
    partial void DeleteDonThuoc(DonThuoc instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertLoaiThuoc(LoaiThuoc instance);
    partial void UpdateLoaiThuoc(LoaiThuoc instance);
    partial void DeleteLoaiThuoc(LoaiThuoc instance);
    #endregion
		
		public DataQuanLyNhaThuocDataContext() : 
				base(global::DAL_QuanLyNhanVien.Properties.Settings.Default.DoAnQuanLyNhaThuocConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyNhaThuocDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyNhaThuocDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyNhaThuocDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyNhaThuocDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LoaiUser> LoaiUsers
		{
			get
			{
				return this.GetTable<LoaiUser>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DonThuoc> DonThuocs
		{
			get
			{
				return this.GetTable<DonThuoc>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<LoaiThuoc> LoaiThuocs
		{
			get
			{
				return this.GetTable<LoaiThuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiUsers")]
	public partial class LoaiUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_loai;
		
		private string _ten_loai;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_loaiChanging(int value);
    partial void Onma_loaiChanged();
    partial void Onten_loaiChanging(string value);
    partial void Onten_loaiChanged();
    #endregion
		
		public LoaiUser()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_loai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_loai
		{
			get
			{
				return this._ma_loai;
			}
			set
			{
				if ((this._ma_loai != value))
				{
					this.Onma_loaiChanging(value);
					this.SendPropertyChanging();
					this._ma_loai = value;
					this.SendPropertyChanged("ma_loai");
					this.Onma_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ten_loai
		{
			get
			{
				return this._ten_loai;
			}
			set
			{
				if ((this._ten_loai != value))
				{
					this.Onten_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_loai = value;
					this.SendPropertyChanged("ten_loai");
					this.Onten_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiUser_User", Storage="_Users", ThisKey="ma_loai", OtherKey="ma_loai")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.LoaiUser = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.LoaiUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ma_loai;
		
		private string _ho_ten;
		
		private string _email;
		
		private string _mat_khau;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<DonThuoc> _DonThuocs;
		
		private EntityRef<LoaiUser> _LoaiUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onma_loaiChanging(int value);
    partial void Onma_loaiChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public User()
		{
			this._DonThuocs = new EntitySet<DonThuoc>(new Action<DonThuoc>(this.attach_DonThuocs), new Action<DonThuoc>(this.detach_DonThuocs));
			this._LoaiUser = default(EntityRef<LoaiUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_loai", DbType="Int NOT NULL")]
		public int ma_loai
		{
			get
			{
				return this._ma_loai;
			}
			set
			{
				if ((this._ma_loai != value))
				{
					if (this._LoaiUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_loaiChanging(value);
					this.SendPropertyChanging();
					this._ma_loai = value;
					this.SendPropertyChanged("ma_loai");
					this.Onma_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(MAX)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_DonThuoc", Storage="_DonThuocs", ThisKey="id", OtherKey="id_nhan_vien")]
		public EntitySet<DonThuoc> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiUser_User", Storage="_LoaiUser", ThisKey="ma_loai", OtherKey="ma_loai", IsForeignKey=true)]
		public LoaiUser LoaiUser
		{
			get
			{
				return this._LoaiUser.Entity;
			}
			set
			{
				LoaiUser previousValue = this._LoaiUser.Entity;
				if (((previousValue != value) 
							|| (this._LoaiUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiUser.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._LoaiUser.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._ma_loai = value.ma_loai;
					}
					else
					{
						this._ma_loai = default(int);
					}
					this.SendPropertyChanged("LoaiUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_khach_hang;
		
		private string _ho_ten;
		
		private string _so_dien_thoai;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<DonThuoc> _DonThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_khach_hangChanging(int value);
    partial void Onid_khach_hangChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonThuocs = new EntitySet<DonThuoc>(new Action<DonThuoc>(this.attach_DonThuocs), new Action<DonThuoc>(this.detach_DonThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonThuoc", Storage="_DonThuocs", ThisKey="id_khach_hang", OtherKey="id_khach_hang")]
		public EntitySet<DonThuoc> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonThuoc")]
	public partial class DonThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_don;
		
		private int _id_loai;
		
		private int _id_thuoc;
		
		private int _id_khach_hang;
		
		private int _id_nhan_vien;
		
		private int _so_luong;
		
		private decimal _gia_tien;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private string _trang_thai;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<User> _User;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<LoaiThuoc> _LoaiThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_donChanging(int value);
    partial void Onid_donChanged();
    partial void Onid_loaiChanging(int value);
    partial void Onid_loaiChanged();
    partial void Onid_thuocChanging(int value);
    partial void Onid_thuocChanged();
    partial void Onid_khach_hangChanging(int value);
    partial void Onid_khach_hangChanged();
    partial void Onid_nhan_vienChanging(int value);
    partial void Onid_nhan_vienChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void Ongia_tienChanging(decimal value);
    partial void Ongia_tienChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public DonThuoc()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._User = default(EntityRef<User>);
			this._Thuoc = default(EntityRef<Thuoc>);
			this._LoaiThuoc = default(EntityRef<LoaiThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_don", DbType="Int NOT NULL")]
		public int id_don
		{
			get
			{
				return this._id_don;
			}
			set
			{
				if ((this._id_don != value))
				{
					this.Onid_donChanging(value);
					this.SendPropertyChanging();
					this._id_don = value;
					this.SendPropertyChanged("id_don");
					this.Onid_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", DbType="Int NOT NULL")]
		public int id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					if (this._LoaiThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuoc", DbType="Int NOT NULL")]
		public int id_thuoc
		{
			get
			{
				return this._id_thuoc;
			}
			set
			{
				if ((this._id_thuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_thuocChanging(value);
					this.SendPropertyChanging();
					this._id_thuoc = value;
					this.SendPropertyChanged("id_thuoc");
					this.Onid_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khach_hang", DbType="Int NOT NULL")]
		public int id_khach_hang
		{
			get
			{
				return this._id_khach_hang;
			}
			set
			{
				if ((this._id_khach_hang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._id_khach_hang = value;
					this.SendPropertyChanged("id_khach_hang");
					this.Onid_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="Int NOT NULL")]
		public int id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_nhan_vien = value;
					this.SendPropertyChanged("id_nhan_vien");
					this.Onid_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_tien", DbType="Decimal(18,2) NOT NULL")]
		public decimal gia_tien
		{
			get
			{
				return this._gia_tien;
			}
			set
			{
				if ((this._gia_tien != value))
				{
					this.Ongia_tienChanging(value);
					this.SendPropertyChanging();
					this._gia_tien = value;
					this.SendPropertyChanged("gia_tien");
					this.Ongia_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(20)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonThuoc", Storage="_KhachHang", ThisKey="id_khach_hang", OtherKey="id_khach_hang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._id_khach_hang = value.id_khach_hang;
					}
					else
					{
						this._id_khach_hang = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_DonThuoc", Storage="_User", ThisKey="id_nhan_vien", OtherKey="id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._id_nhan_vien = value.id;
					}
					else
					{
						this._id_nhan_vien = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_DonThuoc", Storage="_Thuoc", ThisKey="id_thuoc", OtherKey="id_thuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._id_thuoc = value.id_thuoc;
					}
					else
					{
						this._id_thuoc = default(int);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThuoc_DonThuoc", Storage="_LoaiThuoc", ThisKey="id_loai", OtherKey="id_loai", IsForeignKey=true)]
		public LoaiThuoc LoaiThuoc
		{
			get
			{
				return this._LoaiThuoc.Entity;
			}
			set
			{
				LoaiThuoc previousValue = this._LoaiThuoc.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThuoc.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._LoaiThuoc.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._id_loai = value.id_loai;
					}
					else
					{
						this._id_loai = default(int);
					}
					this.SendPropertyChanged("LoaiThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_thuoc;
		
		private int _id_loai;
		
		private string _ten_thuoc;
		
		private string _thanh_phan;
		
		private string _mo_ta;
		
		private decimal _gia_tien;
		
		private string _noi_san_xuat;
		
		private string _hinh_anh;
		
		private System.Nullable<System.DateTime> _ngay_san_xuat;
		
		private System.Nullable<System.DateTime> _ngay_het_han;
		
		private string _trang_thai;
		
		private EntitySet<DonThuoc> _DonThuocs;
		
		private EntityRef<LoaiThuoc> _LoaiThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thuocChanging(int value);
    partial void Onid_thuocChanged();
    partial void Onid_loaiChanging(int value);
    partial void Onid_loaiChanged();
    partial void Onten_thuocChanging(string value);
    partial void Onten_thuocChanged();
    partial void Onthanh_phanChanging(string value);
    partial void Onthanh_phanChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Ongia_tienChanging(decimal value);
    partial void Ongia_tienChanged();
    partial void Onnoi_san_xuatChanging(string value);
    partial void Onnoi_san_xuatChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Onngay_san_xuatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_san_xuatChanged();
    partial void Onngay_het_hanChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_het_hanChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public Thuoc()
		{
			this._DonThuocs = new EntitySet<DonThuoc>(new Action<DonThuoc>(this.attach_DonThuocs), new Action<DonThuoc>(this.detach_DonThuocs));
			this._LoaiThuoc = default(EntityRef<LoaiThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_thuoc
		{
			get
			{
				return this._id_thuoc;
			}
			set
			{
				if ((this._id_thuoc != value))
				{
					this.Onid_thuocChanging(value);
					this.SendPropertyChanging();
					this._id_thuoc = value;
					this.SendPropertyChanged("id_thuoc");
					this.Onid_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", DbType="Int NOT NULL")]
		public int id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					if (this._LoaiThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_thuoc", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ten_thuoc
		{
			get
			{
				return this._ten_thuoc;
			}
			set
			{
				if ((this._ten_thuoc != value))
				{
					this.Onten_thuocChanging(value);
					this.SendPropertyChanging();
					this._ten_thuoc = value;
					this.SendPropertyChanged("ten_thuoc");
					this.Onten_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_phan", DbType="NVarChar(MAX)")]
		public string thanh_phan
		{
			get
			{
				return this._thanh_phan;
			}
			set
			{
				if ((this._thanh_phan != value))
				{
					this.Onthanh_phanChanging(value);
					this.SendPropertyChanging();
					this._thanh_phan = value;
					this.SendPropertyChanged("thanh_phan");
					this.Onthanh_phanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(MAX)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_tien", DbType="Decimal(18,2) NOT NULL")]
		public decimal gia_tien
		{
			get
			{
				return this._gia_tien;
			}
			set
			{
				if ((this._gia_tien != value))
				{
					this.Ongia_tienChanging(value);
					this.SendPropertyChanging();
					this._gia_tien = value;
					this.SendPropertyChanged("gia_tien");
					this.Ongia_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_san_xuat", DbType="NVarChar(200)")]
		public string noi_san_xuat
		{
			get
			{
				return this._noi_san_xuat;
			}
			set
			{
				if ((this._noi_san_xuat != value))
				{
					this.Onnoi_san_xuatChanging(value);
					this.SendPropertyChanging();
					this._noi_san_xuat = value;
					this.SendPropertyChanged("noi_san_xuat");
					this.Onnoi_san_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(255)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_san_xuat", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_san_xuat
		{
			get
			{
				return this._ngay_san_xuat;
			}
			set
			{
				if ((this._ngay_san_xuat != value))
				{
					this.Onngay_san_xuatChanging(value);
					this.SendPropertyChanging();
					this._ngay_san_xuat = value;
					this.SendPropertyChanged("ngay_san_xuat");
					this.Onngay_san_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_het_han", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_het_han
		{
			get
			{
				return this._ngay_het_han;
			}
			set
			{
				if ((this._ngay_het_han != value))
				{
					this.Onngay_het_hanChanging(value);
					this.SendPropertyChanging();
					this._ngay_het_han = value;
					this.SendPropertyChanged("ngay_het_han");
					this.Onngay_het_hanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_DonThuoc", Storage="_DonThuocs", ThisKey="id_thuoc", OtherKey="id_thuoc")]
		public EntitySet<DonThuoc> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThuoc_Thuoc", Storage="_LoaiThuoc", ThisKey="id_loai", OtherKey="id_loai", IsForeignKey=true)]
		public LoaiThuoc LoaiThuoc
		{
			get
			{
				return this._LoaiThuoc.Entity;
			}
			set
			{
				LoaiThuoc previousValue = this._LoaiThuoc.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThuoc.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._LoaiThuoc.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._id_loai = value.id_loai;
					}
					else
					{
						this._id_loai = default(int);
					}
					this.SendPropertyChanged("LoaiThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiThuoc")]
	public partial class LoaiThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_loai;
		
		private string _ten_loai;
		
		private string _trang_thai;
		
		private EntitySet<DonThuoc> _DonThuocs;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loaiChanging(int value);
    partial void Onid_loaiChanged();
    partial void Onten_loaiChanging(string value);
    partial void Onten_loaiChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public LoaiThuoc()
		{
			this._DonThuocs = new EntitySet<DonThuoc>(new Action<DonThuoc>(this.attach_DonThuocs), new Action<DonThuoc>(this.detach_DonThuocs));
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_loai
		{
			get
			{
				return this._ten_loai;
			}
			set
			{
				if ((this._ten_loai != value))
				{
					this.Onten_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_loai = value;
					this.SendPropertyChanged("ten_loai");
					this.Onten_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThuoc_DonThuoc", Storage="_DonThuocs", ThisKey="id_loai", OtherKey="id_loai")]
		public EntitySet<DonThuoc> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThuoc_Thuoc", Storage="_Thuocs", ThisKey="id_loai", OtherKey="id_loai")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThuoc = this;
		}
		
		private void detach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThuoc = null;
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThuoc = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThuoc = null;
		}
	}
}
#pragma warning restore 1591
